const fs = require('fs');

// Read the CSV file (UTF-8)
let content = fs.readFileSync('sample_inventory.csv', 'utf8');

// Remove BOM if present
if (content.charCodeAt(0) === 0xFEFF) {
    content = content.slice(1);
}

const lines = content.split('\n');
const sqlRows = [];

for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    // Use a regex to handle quoted fields with commas
    const parts = line.match(/(".*?"|[^",\s]+)(?=\s*,|\s*$)/g) || [];
    if (parts.length < 7) {
        // Fallback for simple splitting if regex fails (though less robust)
        const simpleParts = line.split(',');
        if (simpleParts.length < 7) continue;
    }

    // Better CSV parser for a single line
    const parseCSVLine = (text) => {
        const result = [];
        let cur = '';
        let inQuote = false;
        for (let j = 0; j < text.length; j++) {
            const char = text[j];
            if (char === '"') inQuote = !inQuote;
            else if (char === ',' && !inQuote) {
                result.push(cur);
                cur = '';
            } else {
                cur += char;
            }
        }
        result.push(cur);
        return result;
    };

    const row = parseCSVLine(line);

    const cleanNum = (str) => {
        if (!str) return 0;
        return parseFloat(str.replace(/[",]/g, '')) || 0;
    };

    const values = [
        row[0] ? `'${row[0].replace(/'/g, "''")}'` : 'NULL', // part_number
        row[1] ? `'${row[1].replace(/'/g, "''")}'` : 'NULL', // product_name
        row[2] ? `'${row[2].replace(/'/g, "''")}'` : 'NULL', // category
        cleanNum(row[3]), // unit_price
        cleanNum(row[4]), // p2_quantity
        cleanNum(row[5]), // p3_quantity
        cleanNum(row[6])  // total_amount
    ];

    sqlRows.push(`(${values.join(', ')})`);
}

const batchSize = 100;
let finalSql = `-- Create Table
CREATE TABLE IF NOT EXISTS public.inventory_valuation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT,
    product_name TEXT,
    category TEXT,
    unit_price NUMERIC DEFAULT 0,
    p2_quantity INTEGER DEFAULT 0,
    p3_quantity INTEGER DEFAULT 0,
    total_amount NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Delete existing data for a fresh import (Optional)
-- TRUNCATE public.inventory_valuation;

-- Batch Insert Data\n`;

for (let i = 0; i < sqlRows.length; i += batchSize) {
    const chunk = sqlRows.slice(i, i + batchSize);
    finalSql += `INSERT INTO public.inventory_valuation (
    part_number, product_name, category, unit_price, p2_quantity, p3_quantity, total_amount
) VALUES \n${chunk.join(',\n')};\n\n`;
}

fs.writeFileSync('import_valuation.sql', finalSql);
console.log(`Generated SQL for ${sqlRows.length} rows.`);
