-- Recreate the "P2 position" table with correct columns for layout grid storage
DROP TABLE IF EXISTS public."P2 position";

CREATE TABLE public."P2 position" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    row_index INTEGER NOT NULL,
    col0 TEXT,
    col1 TEXT,
    col2 TEXT,
    col3 TEXT,
    col4 TEXT,
    col5 TEXT,
    col6 TEXT,
    col7 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security (RLS) for anonymous access, or enable with open policy
ALTER TABLE public."P2 position" DISABLE ROW LEVEL SECURITY;
