-- Recreate the "P3 position" table with correct columns for P3 layout grid storage
DROP TABLE IF EXISTS public."P3 position";

CREATE TABLE public."P3 position" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    row_index INTEGER NOT NULL,
    col0 TEXT,
    col1 TEXT,
    col2 TEXT,
    col3 TEXT,
    col4 TEXT,
    col5 TEXT,
    col6 TEXT,
    col7 TEXT,
    col8 TEXT,
    col9 TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security (RLS) for anonymous access
ALTER TABLE public."P3 position" DISABLE ROW LEVEL SECURITY;
